Algoritmo " qual é seu nome "


Var
 nome: caractere
 resposta: caractere

Inicio
 escreval (" qual é seu nome ?")
 leia ( nome )
 escreval ("seja bem vindo ao mundo encatado ", nome)
 escreval (" voce esta pronto pra descobrir algo inesquecivel ?" )
 leia ( resposta )
 se (resposta = "sim") entao
      escreval("Te amo S2 S2 S2 S2 ")
   senao
      escreval("Talvez em outro momento! ??")
      fimse
Fimalgoritmo