Algoritmo "tabuada do 3 "
Var
  aluno: caractere
Inicio
   escreval ("aluno<a>: ")
   leia(aluno)
   escreval ("tabuada de 3 :")
   escreval("3 x 1 = 3"  )
   escreval("3 x 2 = 6"  )
   escreval("3 x 3 = 9"  )
   escreval("3 x 4 = 12" )
   escreval ("3 x 5 = 15")
   escreval("3 x 6 = 18"  )
   escreval("3 x 7 = 21"  )
   escreval("3 x 8 = 24"  )
   escreval("3 x 9 = 27"  )
   escreval("3 x 10 = 30"  )
Fimalgoritmo